name: secure_notepad
description: Secure CLI notepad with end-to-end encryption.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.5.0
  cryptography: ^2.5.0
  path: ^1.9.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0